### ISSUE TITLE
[FEATURE] Need a state management tool

### ISSUE THREAD

**Issue by azrael3199** [azrael3199/goalkeeper-web#5]
**Is your feature request related to a problem? Please describe.**

Currently for the 0.1 version we do not need to manage complicated states for components, but when developing later versions the states will eventually become more complicated.

**Describe the solution you'd like**

Since the app is still in its infancy, I believe this is the correct time to setup a State management tool like Redux. This will prevent headaches later on.

**Describe alternatives you've considered**

Few of the alternatives to Redux that we can have are:
* Zustand: https://github.com/pmndrs/zustand
* Rematch: https://rematchjs.org/
* Recoil: https://recoiljs.org/

**Comment by azrael3199** [comment]
@prakriti150794 and @shubham-cpp We could have a discussion here about what tool we could use

**Comment by shubham-cpp** [comment]
Zustand is the obvious choice IMO. Complete type safety plus integrates very nicely with [zod](https://github.com/colinhacks/zod).

Alternative to recoil is [jotai](https://jotai.org/). But I don't think we would need an atomic state library we can just use [react-query](https://tanstack.com/query/v4/docs/react/overview)

**Comment by azrael3199** [comment]
> Zustand is the obvious choice IMO. Complete type safety plus integrates very nicely with [zod](https://github.com/colinhacks/zod).
> 
> Alternative to recoil is [jotai](https://jotai.org/). But I don't think we would need an atomic state library we can just use [react-query](https://tanstack.com/query/v4/docs/react/overview)

We could go ahead with Zustand, but could you please list down a few advantages that you think we might get right now or in the future if we choose to move forward with this? This would add justification for other contributors as well.

**Comment by azrael3199** [comment]
I could find a link in support of Zustand over Redux and......welp: https://youtu.be/DK-S4ZcmDcE

**Comment by shubham-cpp** [comment]
What about react-query ? @azrael3199

**Comment by azrael3199** [comment]
@shubham-cpp I was thinking of using react-query along with Zustand. Like Zustand would replace Redux and react-query replaces axios. What do you think?

**Comment by shubham-cpp** [comment]
React-query is not a replacement to axios, its more of how we cache response data.
I think keeping axios is fine or else we would need to cover edge cases of fetchApi like (res.ok,etc).
But yes for our use case we can use react-query for less complex(atomic) global states(states that need to be accessed globally without prop drilling).

**Comment by azrael3199** [comment]
@shubham-cpp I'm fine with react-query as well. I was just excited to try out Zustand :)

**Comment by shubham-cpp** [comment]
Yes using zustand as our primary state management tool and using react-query to cache response from apis

**Comment by azrael3199** [comment]
Cool I think we should start then

**Comment by azrael3199** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add State Management Tools: Zustand and react-query](https://trello.com/c/LhxnkX2h/1-add-state-management-tools-zustand-and-react-query)
