### ISSUE TITLE
[FEATURE] Need to setup GitHub actions to run unit and integrations tests on push

### ISSUE THREAD

**Issue by azrael3199** [azrael3199/goalkeeper-web#7]
**Is your feature request related to a problem? Please describe.**
When new components will be added to the app, unit and integration tests need to be written for the code to check its sanity. These tests eventually get heavier to run locally and thus need to be run after a push to a branch in repo and validated as status checks instead.

**Describe the solution you'd like**
Currently one of the favored solutions is to setup GitHub actions flow to trigger running the tests online instead of locally. The GitHub workflow when any code is pushed onto a branch, gets triggered and returns a status about whether all the tests passed or any failed. This status can be put as a prerequisite to enable or disable the merging of a PR.
 
**Describe alternatives you've considered**

**Additional context**

**Comment by shubham-cpp** [comment]
We would probably need to divide this task into two.
- [ ] Setup/Configure Testing Environment with Jest/React-testing-library
- [ ] Setup/Configure Github CI.

Question:
1. Do we need Cypress(End-to-End Testing) as well?

For reference we can see

**Comment by shubham-cpp** [comment]
For more: https://github.com/vitejs/awesome-vite#react
